### ISSUE TITLE
Unable to import`neo4j-p2p-data.dump` into AuraDB (Neo4j v5)

### ISSUE THREAD

**Issue by hisplan** [neo4j-product-examples/demo-fraud-detection-with-p2p#4]
I'm trying to import `neo4j-p2p-data.dump` into AuraDB (Neo4j v5), but I'm getting an error `Loading failed` (screenshot attached below).

I got the dump file from here: https://drive.google.com/drive/folders/1LaNFObKnZb1Ty8T7kPLCYlXDUlHU7FGa

I noticed that `neo4j-p2p-data.dump` is for Neo4j version 4.4. Is that the problem? If so, where can I get the dump file compatible with Neo4j v5? I'd like to explore this graph using AuraDB.

Thanks.

![loading-failed](https://user-images.githubusercontent.com/12453582/215535049-64a79349-b630-400e-b739-e9ee1919e5e6.jpg)

**Comment by smitapadhy-84** [comment]
I am also facing the same issue.

**Comment by Najmieh87** [comment]
me too.

**Comment by zach-blumenfeld** [comment]
Old thread.  But this should be fixed now with an updated dump file for Neo4j 5.  The 4.4 dump file is still there for back compatibility but relabedled to `neo4j-p2p-data_v44.dump`
